name: Pylint

on:
  push:
    branches:
      - main
      - develop

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout SCRUTINY
        uses: actions/checkout@master
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Pylint
        uses: cclauss/GitHub-Action-for-pylint@master
        with:
          args: "pylint *.py scrutiny"
