on:
  push:
    branches:
      - main
      - develop
name: Pylint
jobs:
  gitHubActionForPylint:
    name: GitHub Action for pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@master
      with:
        args: "pip install -r requirements.txt ; pylint --disable=too-few-public-methods,missing-module-docstring,R0801,broad-except,invalid-name,use-a-generator,too-many-instance-attributes *.py scrutiny"
